spring:
#  datasource:
#    url: "jdbc:h2:tcp://localhost/~/dbs/toy_blog"
#    username: "sa"
#    password:
#    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
#    url: "jdbc:postgresql://localhost:5432/solvelog"
    url: "jdbc:postgresql://postgresdb:5432/solvelog"
    username: "solvelog_admin"
    password: "${SOLVELOG_DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000 #ms
      ssl:
        enabled: false
  #      password:

  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc.time_zone: Asia/Seoul

logging.level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace

cookie:
  secure: true
  same-site: None

cloud:
  aws:
    s3:
      bucket: ${SOLVELOG_BUCKET}
    region:
      static: ap-northeast-2