ALTER TABLE public.user_statistic
    RENAME COLUMN count TO statistic_count;

ALTER TABLE public.user_statistic
    ADD COLUMN created_date timestamp(6) without time zone;

ALTER TABLE public.user_statistic
    ADD COLUMN modified_date timestamp(6) without time zone;

ALTER TABLE public.user_statistic
ALTER COLUMN user_statistic_id
ADD GENERATED BY DEFAULT AS IDENTITY;